// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebSite.Server.Data;

#nullable disable

namespace MovieWebSite.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241026203422_changeUserNameToId")]
    partial class changeUserNameToId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Model.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Shonen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Idol"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Game"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 19,
                            Name = "War"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Mecha"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Reality"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Adventure"
                        });
                });

            modelBuilder.Entity("Server.Model.Models.CategoryFilm", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("CategoryFilms");

                    b.HasData(
                        new
                        {
                            CategoryId = 28,
                            FilmId = 1
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 1
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 1
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 1
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 2
                        },
                        new
                        {
                            CategoryId = 2,
                            FilmId = 2
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 3
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 3
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 3
                        },
                        new
                        {
                            CategoryId = 11,
                            FilmId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            FilmId = 4
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 4
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 5
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 5
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 5
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 6
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 6
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 6
                        },
                        new
                        {
                            CategoryId = 14,
                            FilmId = 7
                        },
                        new
                        {
                            CategoryId = 18,
                            FilmId = 7
                        },
                        new
                        {
                            CategoryId = 7,
                            FilmId = 7
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 8
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 8
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 8
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 9
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 9
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 9
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 10
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 10
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 10
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 11
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 11
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 11
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 12
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 12
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 12
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 13
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 13
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 14
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 14
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 14
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 15
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 15
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 15
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 16
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 16
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 16
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 17
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 17
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 17
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 18
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 18
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 18
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 19
                        },
                        new
                        {
                            CategoryId = 23,
                            FilmId = 19
                        },
                        new
                        {
                            CategoryId = 11,
                            FilmId = 19
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 20
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 20
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 20
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 21
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 21
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 21
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 21
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 22
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 22
                        },
                        new
                        {
                            CategoryId = 17,
                            FilmId = 22
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 22
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 23
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 23
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 23
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 23
                        },
                        new
                        {
                            CategoryId = 17,
                            FilmId = 24
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 24
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 24
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 24
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 25
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 25
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 25
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 25
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 26
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 27
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 27
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 28
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 29
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 30
                        },
                        new
                        {
                            CategoryId = 11,
                            FilmId = 31
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 32
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 32
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 33
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 34
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 34
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 35
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 36
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 36
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 37
                        },
                        new
                        {
                            CategoryId = 5,
                            FilmId = 38
                        },
                        new
                        {
                            CategoryId = 22,
                            FilmId = 39
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 40
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 40
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 41
                        },
                        new
                        {
                            CategoryId = 4,
                            FilmId = 42
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 43
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 43
                        },
                        new
                        {
                            CategoryId = 6,
                            FilmId = 44
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 44
                        },
                        new
                        {
                            CategoryId = 10,
                            FilmId = 45
                        },
                        new
                        {
                            CategoryId = 1,
                            FilmId = 45
                        },
                        new
                        {
                            CategoryId = 14,
                            FilmId = 45
                        },
                        new
                        {
                            CategoryId = 2,
                            FilmId = 46
                        },
                        new
                        {
                            CategoryId = 2,
                            FilmId = 47
                        },
                        new
                        {
                            CategoryId = 2,
                            FilmId = 48
                        },
                        new
                        {
                            CategoryId = 2,
                            FilmId = 49
                        },
                        new
                        {
                            CategoryId = 8,
                            FilmId = 50
                        },
                        new
                        {
                            CategoryId = 27,
                            FilmId = 51
                        },
                        new
                        {
                            CategoryId = 9,
                            FilmId = 52
                        },
                        new
                        {
                            CategoryId = 25,
                            FilmId = 53
                        });
                });

            modelBuilder.Entity("Server.Model.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommnentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Server.Model.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("VidName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Server.Model.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlurHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilmPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Masayuki Kojima",
                            FilmPath = "Made_in_Abyss_volume_1_cover.jpg",
                            Synopsis = "The story takes place in the fictional town of Orth, where humans are drawn to a mysterious pit known as the \"Abyss\". The series follows Riko, a young orphan, who becomes obsessed with exploring the Abyss, despite the danger and unknown terrors that lurk within. Alongside her companion, Reg, they delve into the depths of the Abyss, uncovering secrets and facing challenges that threaten their lives. The series explores themes of discovery, friendship, and the human condition.",
                            Title = "Made in Abyss",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Shawn Levy",
                            FilmPath = "2dc59b7ae3022ab3ea57c1d6ad94399a.jpg",
                            Synopsis = "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
                            Title = "Deadpool & Wolverine",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Christopher Nolan",
                            FilmPath = "MV5BMjExMjkwNTQ0Nl5BMl5BanBnXkFtZTcwNTY0OTk1Mw@@._V1_.jpg",
                            Synopsis = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                            Title = "Inception",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Ridley Scott",
                            FilmPath = "Gladiator_(2000_film_poster).png",
                            Synopsis = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Title = "Gladiator",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 5,
                            Director = "Hayao Miyazaki",
                            FilmPath = "MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Synopsis = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
                            Title = "Spirited Away",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Christopher Nolan",
                            FilmPath = "MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
                            Synopsis = "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Title = "The Dark Knight",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Damien Chazelle",
                            FilmPath = "MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_.jpg",
                            Synopsis = "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
                            Title = "La La Land",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 8,
                            Director = "The Duffer Brothers",
                            FilmPath = "image5.jpg",
                            Synopsis = "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
                            Title = "Stranger Things",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 9,
                            Director = "Jon Favreau",
                            FilmPath = "var-www-share-shop-live-src-media-import-iadx4-095-the-mandalorian-gunslingers-web.jpg",
                            Synopsis = "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
                            Title = "The Mandalorian",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 10,
                            Director = "Bong Joon-ho",
                            FilmPath = "MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
                            Synopsis = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Title = "Parasite",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 11,
                            Director = "Lauren Schmidt Hissrich",
                            FilmPath = "p17580215_b_v13_ab.jpg",
                            Synopsis = "Geralt of Rivia, a mutated monster hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
                            Title = "The Witcher",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 12,
                            Director = "Anthony and Joe Russo",
                            FilmPath = "MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg",
                            Synopsis = "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
                            Title = "Avengers: Endgame",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 13,
                            Director = "Vince Gilligan",
                            FilmPath = "MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
                            Synopsis = "A high school chemistry teacher turned methamphetamine manufacturer partners with a former student in a gradual descent into the criminal underworld.",
                            Title = "Breaking Bad",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 14,
                            Director = "James Cameron",
                            FilmPath = "MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
                            Title = "Avatar",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 15,
                            Director = "David Benioff, D.B. Weiss",
                            FilmPath = "MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Synopsis = "Nine noble families wage war against each other in order to gain control over the mythical land of Westeros.",
                            Title = "Game of Thrones",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 16,
                            Director = "The Wachowskis",
                            FilmPath = "613ypTLZHsL._AC_UF894,1000_QL80_.jpg",
                            Synopsis = "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.",
                            Title = "The Matrix",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 17,
                            Director = "Mark Gatiss, Steven Moffat",
                            FilmPath = "MV5BNTQzNGZjNDEtOTMwYi00MzFjLWE2ZTYtYzYxYzMwMjZkZDc5XkEyXkFqcGc@._V1_.jpg",
                            Synopsis = "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
                            Title = "Sherlock",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 18,
                            Director = "George Miller",
                            FilmPath = "p10854488_p_v8_ac.jpg",
                            Synopsis = "In a post-apocalyptic wasteland, Max teams up with a mysterious woman, Furiosa, to try and survive.",
                            Title = "Mad Max: Fury Road",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 19,
                            Director = "Peter Morgan",
                            FilmPath = "71f97nf-u9L._AC_UF1000,1000_QL80_.jpg",
                            Synopsis = "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
                            Title = "The Crown",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 20,
                            Director = "Christopher Nolan",
                            FilmPath = "MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
                            Synopsis = "A team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival.",
                            Title = "Interstellar",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 21,
                            Director = "Tetsurō Araki",
                            FilmPath = "p10701949_b_v8_ah.jpg",
                            Synopsis = "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
                            Title = "Attack on Titan",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 22,
                            Director = "Masayuki Kojima",
                            FilmPath = "unnamed.jpg",
                            Synopsis = "Riko, Reg, and their new friend, Nanachi, continue their journey down the Abyss and arrive at the 5th layer. But in order for them to continue to the 6th layer, they must encounter the haunting figure of Nanachi's past: Bondrewd the Novel.",
                            Title = "Made In Abyss: Dawn of The Deep Soul",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 23,
                            Director = "Hayato Date",
                            FilmPath = "MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "Follows Naruto Uzumaki, a young ninja with dreams of becoming the strongest ninja and leader of his village.",
                            Title = "Naruto",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 24,
                            Director = "Hayao Miyazaki",
                            FilmPath = "MV5BYWM3MDE3YjEtMzIzZC00ODE5LTgxNTItNmUyMTBkM2M2NmNiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "When two girls move to the countryside to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.",
                            Title = "My Neighbor Totoro",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 25,
                            Director = "Haruo Sotozaki",
                            FilmPath = "MV5BYTIxNjk3YjItYmYzMC00ZTdmLTk0NGUtZmNlZTA0NWFkZDMwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Synopsis = "A young boy becomes a demon slayer to avenge his family and cure his sister.",
                            Title = "Demon Slayer: Kimetsu no Yaiba",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 26,
                            Director = "Frank Darabont",
                            FilmPath = "MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
                            Synopsis = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Title = "The Shawshank Redemption",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 27,
                            Director = "Peter Jackson",
                            FilmPath = "MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Title = "The Lord of the Rings: The Return of the King",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 28,
                            Director = "Quentin Tarantino",
                            FilmPath = "MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            Synopsis = "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Title = "Pulp Fiction",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 29,
                            Director = "Francis Ford Coppola",
                            FilmPath = "MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Title = "The Godfather",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 30,
                            Director = "Sidney Lumet",
                            FilmPath = "12_Angry_Men_(1957_film_poster).jpg",
                            Synopsis = "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
                            Title = "12 Angry Men",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 31,
                            Director = "Steven Spielberg",
                            FilmPath = "MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Synopsis = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Title = "Schindler's List",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 32,
                            Director = "Peter Jackson",
                            FilmPath = "MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_.jpg",
                            Synopsis = "A hobbit, a wizard, a dwarf, an elf, and three men embark on a perilous journey to destroy the One Ring and save Middle-earth from Sauron's darkness.",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 33,
                            Director = "Miloš Forman",
                            FilmPath = "MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "A criminal pleads insanity and is admitted to a mental institution, where he challenges the authority of the strict Nurse Ratched.",
                            Title = "One Flew Over the Cuckoo's Nest",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 34,
                            Director = "Christopher Nolan",
                            FilmPath = "MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "Eight years after the Joker's reign of terror, Batman must face his most formidable foe yet: Bane.",
                            Title = "The Dark Knight Rises",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 35,
                            Director = "Quentin Tarantino",
                            FilmPath = "MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
                            Synopsis = "In Nazi-occupied France during World War II, a group of Jewish-American guerrilla soldiers known as \"The Basterds\" are chosen specifically to spread fear throughout the Third Reich by scalping and brutally killing Nazis.",
                            Title = "Inglourious Basterds",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 36,
                            Director = "Peter Jackson",
                            FilmPath = "MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "While Frodo and Sam edge closer to Mordor with the One Ring, Aragorn, Legolas and Gimli search for Merry and Pippin, captured by the enemy.",
                            Title = "The Lord of the Rings: The Two Towers",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 37,
                            Director = "Martin Scorsese",
                            FilmPath = "MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
                            Synopsis = "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his Mob partners Jimmy Conway and Tommy DeVito in the Italian-American Mafia.",
                            Title = "Goodfellas",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 38,
                            Director = "David Fincher",
                            FilmPath = "MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Synopsis = "Two detectives hunt for a serial killer who is using the seven deadly sins as a motif for his murders.",
                            Title = "Se7en",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 39,
                            Director = "David Fincher",
                            FilmPath = "MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg",
                            Synopsis = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much darker.",
                            Title = "Fight Club",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 40,
                            Director = "Irvin Kershner",
                            FilmPath = "71ABa3+0B1L._AC_UF1000,1000_QL80_.jpg",
                            Synopsis = "After the Rebel Alliance's victory on Yavin, Luke Skywalker trains as a Jedi Knight under Yoda while his friends evade the Galactic Empire.",
                            Title = "Star Wars: Episode V - The Empire Strikes Back",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 41,
                            Director = "Jonathan Demme",
                            FilmPath = "MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Synopsis = "A young FBI agent seeks the advice of imprisoned serial killer Hannibal Lecter to apprehend another serial killer known as \"Buffalo Bill\".",
                            Title = "The Silence of the Lambs",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 42,
                            Director = "Frank Capra",
                            FilmPath = "1-7952587233.jpg",
                            Synopsis = "An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.",
                            Title = "It's a Wonderful Life",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 43,
                            Director = "George Lucas",
                            FilmPath = "612h-jwI+EL._AC_UF1000,1000_QL80_.jpg",
                            Synopsis = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
                            Title = "Star Wars: Episode IV - A New Hope",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 44,
                            Director = "Lilly Wachowski, Lana Wachowski",
                            FilmPath = "MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
                            Synopsis = "Neo and Trinity continue their fight against the machines, but they soon discover that they are not alone in their quest.",
                            Title = "The Matrix: Reloaded",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 45,
                            Director = "Gore Verbinski",
                            FilmPath = "pirates-of-the-caribbean-poster.jpg",
                            Synopsis = "Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save his love, Elizabeth Swann, from cursed pirates who become undead skeletons in moonlight.",
                            Title = "Pirates of the Caribbean: The Curse of the Black Pearl",
                            Type = "Movie"
                        },
                        new
                        {
                            Id = 46,
                            Director = "Greg Daniels",
                            FilmPath = "91d053F2aKL._AC_UF894,1000_QL80_.jpg",
                            Synopsis = "A mockumentary-style sitcom that follows the employees at Dunder Mifflin.",
                            Title = "The Office",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 47,
                            Director = "David Crane, Marta Kauffman",
                            FilmPath = "MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "Follows the personal and professional lives of six friends living in Manhattan.",
                            Title = "Friends",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 48,
                            Director = "Chuck Lorre, Bill Prady",
                            FilmPath = "the-big-bang-theory-the-poster-collection-9781608876136_hr.jpg",
                            Synopsis = "A comedy about brilliant physicists Leonard and Sheldon who are socially awkward but intellectually brilliant.",
                            Title = "The Big Bang Theory",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 49,
                            Director = "Dan Goor, Michael Schur",
                            FilmPath = "MV5BNzVkYWY4NzYtMWFlZi00YzkwLThhZDItZjcxYTU4ZTMzMDZmXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg",
                            Synopsis = "Detective Jake Peralta, a talented and carefree detective with the best arrest record, has never had to follow the rules too closely or work very hard.",
                            Title = "Brooklyn Nine-Nine",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 50,
                            Director = "Justin Roiland, Dan Harmon",
                            FilmPath = "MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_FMjpg_UX1000_.jpg",
                            Synopsis = "An animated series that follows the misadventures of Rick Sanchez, a cynical mad scientist, and his good-hearted grandson Morty Smith.",
                            Title = "Rick and Morty",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 51,
                            Director = "Michael Schur",
                            FilmPath = "p12900282_b_v8_aa.jpg",
                            Synopsis = "After her death, Eleanor Shellstrop finds herself in the \"good place\" (heaven) due to a case of mistaken identity.",
                            Title = "The Good Place",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 52,
                            Director = "Jonathan Nolan, Lisa Joy",
                            FilmPath = "MV5BZDg1OWRiMTktZDdiNy00NTZlLTg2Y2EtNWRiMTcxMGE5YTUxXkEyXkFqcGdeQXVyMTM2MDY0OTYx._V1_.jpg",
                            Synopsis = "Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
                            Title = "Westworld",
                            Type = "TV-Series"
                        },
                        new
                        {
                            Id = 53,
                            Director = "Craig Mazin",
                            FilmPath = "MV5BOTJiOWExNWEtYzE1ZS00NDJmLWFiY2ItYTNjMWZiNTQ2ZDIwXkEyXkFqcGc@._V1_.jpg",
                            Synopsis = "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
                            Title = "Chernobyl",
                            Type = "TV-Series"
                        });
                });

            modelBuilder.Entity("Server.Model.Models.UserFilm", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AddPlaylistOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ViewedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FilmId");

                    b.ToTable("UserFilms");
                });

            modelBuilder.Entity("Server.Model.Models.CategoryFilm", b =>
                {
                    b.HasOne("Server.Model.Models.Category", "Category")
                        .WithMany("CategoryFilms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Model.Models.Film", "Film")
                        .WithMany("CategoryFilms")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Server.Model.Models.Comment", b =>
                {
                    b.HasOne("Server.Model.Models.Episode", "Episode")
                        .WithMany("Comments")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("Server.Model.Models.Episode", b =>
                {
                    b.HasOne("Server.Model.Models.Film", "Film")
                        .WithMany("Episodes")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Server.Model.Models.UserFilm", b =>
                {
                    b.HasOne("Server.Model.Models.Film", "Film")
                        .WithMany("UserFilms")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("Server.Model.Models.Category", b =>
                {
                    b.Navigation("CategoryFilms");
                });

            modelBuilder.Entity("Server.Model.Models.Episode", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Server.Model.Models.Film", b =>
                {
                    b.Navigation("CategoryFilms");

                    b.Navigation("Episodes");

                    b.Navigation("UserFilms");
                });
#pragma warning restore 612, 618
        }
    }
}
